#!/bin/bash

echo "🚀 Email Analysis Backend - Render Deployment Guide"
echo "=================================================="
echo ""
echo "📋 Deployment Options:"
echo "1. Automatic (using render.yaml) - Recommended"
echo "2. Manual Web Service creation"
echo "3. Docker deployment"
echo ""
echo "🔗 Render Dashboard: https://dashboard.render.com"
echo ""
echo "📝 Steps:"
echo "1. Connect your GitHub repository to Render"
echo "2. Create a new Blueprint or Web Service"
echo "3. Set the following environment variables:"
echo "   • MONGODB_URI"
echo "   • IMAP_USER"
echo "   • IMAP_PASSWORD"
echo "   • FRONTEND_URL"
echo ""
echo "4. Deploy and get your API URL"
echo ""
echo "📖 For detailed instructions, see RENDER-DEPLOYMENT.md"
echo ""
echo "🎯 Your backend will be available at:"
echo "https://your-project-name.onrender.com/api/"
echo ""
echo "✅ Ready to deploy! 🚀"
