services:
  - type: web
    name: email-analysis-backend
    runtime: node
    buildCommand: npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: IMAP_USER
        sync: false
      - key: IMAP_PASSWORD
        sync: false
      - key: IMAP_HOST
        value: imap.gmail.com
      - key: IMAP_PORT
        value: 993
      - key: FRONTEND_URL
        sync: false
      - key: API_BASE_URL
        fromService:
          type: web
          name: email-analysis-backend
          property: host
